### PR TITLE
Data is now read from the SSL server until no more data is available

### LINKED ISSUE #41: Investigate using a while loop to read decrypted data from the OpenSSL server
### Bug Report
Investigate using a while loop to read decrypted data from the OpenSSL server. Currently only one attempt is made to read the decrypted data, which means:
1. If the read fails, another attempt is not made
1. It is possible that not all data will be read

##### OS & Version Information
* SDL Security iOS Version: 1.0
* SDL iOS Version: n/a
* iOS Version: n/a
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #41 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Smoke tests performed.

### Summary
Reading data from the SSL server is now done in a while loop to make sure all data is read before returning.

##### Enhancements
* Data is now read from the SSL server until no more data is available. 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SDLSecurity/SDLTLSEngine.m [hunk 1]
```diff
@@ -418,10 +418,10 @@ - (nullable NSData *)decryptData:(NSData *)encryptedData withError:(NSError * _N
 
 #pragma mark OpenSSL Encryption / Decryption
 
-/// Writes the unencrypted data to the OpenSSL server so it can be encrypted.
+/// Writes the unencrypted data to the OpenSSL server so it can be encrypted and returns the number of bytes successfully written.
 /// @param data The unencrypted data
 /// @param error The error will be set if the data can not be written successfully
-- (int)sdlsec_SSLWriteDataToServer:(NSData *)data withError:(NSError * __autoreleasing*)error {
+- (int)sdlsec_writeToSSLServerUnencryptedData:(NSData *)data withError:(NSError * __autoreleasing*)error {
```
Comment (joeljfischer) [inline SDLSecurity/SDLTLSEngine.m]:
```suggestion
- (int)sdlsec_writeToSSLServerWithUnencryptedData:(NSData *)data withError:(NSError * __autoreleasing*)error {
```

**Review by joeljfischer — CHANGES_REQUESTED** [review]
I don't have a good way to test this project at this point. Do you have recommendations? Should I trust that you've done it well?

File: SDLSecurity/SDLTLSEngine.m (hunk 1 above)
Comment (NicoleYarroch) [reply SDLSecurity/SDLTLSEngine.m]: Fixed. Renamed.

**Review by joeljfischer — APPROVED** [review]
