### PR TITLE
Certificate manager now fails gracefully if response is not formatted as expected

### LINKED ISSUE #47: Parsing invalid JSON should fail gracefully
### Bug Report
If the request for certificate data returns json formatted differently from the expected json format, parsing the json should not crash the app.

##### Reproduction Steps
1. Request certificate data 
1. The response data is formatted differently than the expected format in the `SDLCertificateManager.m` 

##### Expected Behavior
If parsing the response for the certificate data fails, an error should be returned explaining that the response data is not in the correct format. 

##### Observed Behavior
The security library crashes.

##### OS & Version Information
* SDL Security iOS Version: 1.0.0
* SDL iOS Version: 6.4
* iOS Version: n/a
* Testing Against: n/a

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #47 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Smoke tests performed. 

Make sure when testing to clear the device's cache so a new certificate is downloaded.

### Summary
When the request for certificate data returns JSON formatted differently from the expected format, the library now returns an error instead of crashing.

##### Bug Fixes
* Fixed the library crashing if the network request returns a JSON formatted message different from the one it expects.

### Tasks Remaining:
- [x] Test with SDL Core

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SDLSecurity/SDLCertificateManager.m [hunk 1]
```diff
@@ -62,10 +62,16 @@ - (void)retrieveNewCertificateWithAppId:(NSString *)appId completionHandler:(SDL
 
         if (jsonError != nil || jsonDictionary == nil) {
             SDLSecurityLogE(@"Error parsing network request data");
-            return completionHandler(NO, [NSError errorWithDomain:SDLSecurityErrorDomain code:SDLTLSErrorCodeNoCertificate userInfo:@{NSLocalizedDescriptionKey: @"Network request did not return a certificate"}]);
+            return completionHandler(NO, [NSError errorWithDomain:SDLSecurityErrorDomain code:SDLTLSErrorCodeNoCertificate userInfo:@{NSLocalizedDescriptionKey: @"Network request did not return data in the expected format"}]);
         }
 
-        NSData *certificateData = [[NSData alloc] initWithBase64EncodedData:[jsonDictionary valueForKeyPath:@"data.certificate"] options:0];
+        NSString *certificateKey = @"data.certificate";
+        if (![jsonDictionary valueForKeyPath:certificateKey]) {
```
Comment (joeljfischer) [inline SDLSecurity/SDLCertificateManager.m]:
```suggestion
        if ([jsonDictionary valueForKeyPath:certificateKey] == nil) {
```

**Also**
I think you should pull the data out and check if it's `nil` here and use it below. The current way uses `[jsonDictionary valueForKeyPath:certificateKey]` twice. It may be better to do that once and reference the variable instead.

**Review by joeljfischer — CHANGES_REQUESTED** [review]

File: SDLSecurity/SDLCertificateManager.m (hunk 1 above)
Comment (NicoleYarroch) [reply SDLSecurity/SDLCertificateManager.m]: Fixed.

**Review by joeljfischer — APPROVED** [review]
