### PR TITLE
Fixed downloading a certificate from a URL

### LINKED ISSUE #17: Check that certificates can be downloaded from a URL
Check that certificates can be downloaded from a URL, parsed, and saved correctly. The following situations should be handled:
1. No internet connection
1. Poor internet connection
1. Certificate data write fails
1. Certificate data access fails
    * Library crashes here if it attempts to access certificate data that does not exist.
1. Certificate validation fails
1. Handshake fails

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #17 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Summary
* Added a a custom error to all the downloading a certificate fail cases.
* Reduced the timeout interval for a request from 60 seconds to 20 seconds.
* Changed `initWithCertificateServerURL:` in the `_SDLCertificateManager` class to take a `String` instead of a `URL`
* Fixed bug where the certificate directory was not created if the "Application Support" directory did not already exist.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: SDLSecurity/_SDLCertificateManager.m [hunk 1]
```diff
@@ -83,80 +85,58 @@ - (nullable NSData *)certificateData {
...
-            SDLSecurityLogE(@"Security server responded with an error. Response: %@, Error: %@", response, error);
-            completionHandler(NO, error);
-            return;
-        }
+    NSURLSessionConfiguration *sessionConfig = [NSURLSessionConfiguration defaultSessionConfiguration];
+    sessionConfig.timeoutIntervalForRequest = 20.0;
+
+    NSURLSession *session = [NSURLSession sharedSession];
+    __weak typeof(self) weakSelf = self;
+    NSURLSessionDataTask *task = [session dataTaskWithURL:url completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
```
Comment (joeljfischer) [inline SDLSecurity/_SDLCertificateManager.m:104]: The task should probably be stored so that it can be canceled?

**Review by joeljfischer — APPROVED** [review]

File: SDLSecurity/_SDLCertificateManager.m (hunk 1 above)
Comment (NicoleYarroch) [reply SDLSecurity/_SDLCertificateManager.m:104]: I created issue #30 to address this comment.
